export const ROUTE_REQUEST = 'ROUTE_REQUEST';
export const ROUTES_FETCH_STARTED = 'ROUTES_FETCH_STARTED';
export const ROUTES_RESPONSE = 'ROUTES_RESPONSE';
export const ROUTES_FETCH_FAILED = 'ROUTES_FETCH_FAILED';
